### ISSUE TITLE
Unable to run the stateless-simple-query example in local mode.

### ISSUE THREAD

**Issue by netalpha** [lsds/SEEP#30]
I put both seep-system-0.0.1-SNAPSHOT.jar and stateless-simple-query.jar in the dist folder and run:

```
java -jar seep-system-0.0.1-SNAPSHOT.jar Master stateless-simple-query.jar Base
```

It gives me the following errors:

```
java.lang.ClassNotFoundException: Base
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at uk.ac.imperial.lsds.seep.infrastructure.master.MasterController.executeComposeFromQuery(MasterController.java:153)
    at uk.ac.imperial.lsds.seep.Main.executeMaster(Main.java:69)
    at uk.ac.imperial.lsds.seep.Main.main(Main.java:44)
```

I know it can not locate the Base class. Could you please tell me where is the problem? Thanks.

**Comment by shibilyj** [comment]
In my system all the SEEP files are there, but I don't know how to create the snapshot and copy the snapshot to satateless-simple-query/lib. No jarfiles are there in my folder. Kindly give me all the steps to run  first program

**Comment by pgaref** [comment]
@shibilyj did you try running **mvn clean compile assembly:single**
It produces a seep-system-0.0.1-SNAPSHOT.jar under _seep-system/target/_

**Comment by shibilyj** [comment]
Today I downloaded SEEP-master.zip, unzipped and  donemvn clean compile assembly:single  getting the following error

..
 BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: null:jetty-project:pom:9.0.0.v20130308

Reason: Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308

how to solve this

**Comment by shibilyj** [comment]
This is complete report
/SEEP-master$ mvn -e clean compile assembly:single
- Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Reactor build order: 
  [INFO]   seep
  [INFO]   seep-system
  [INFO]   seep-java2sdg
  [INFO]   seep-streamsql
  [INFO]   seep-contribs
  [INFO] ------------------------------------------------------------------------
  [INFO] Building seep
  [INFO]    task-segment: [clean, compile, assembly:single]
  [INFO] ------------------------------------------------------------------------
  [INFO] [clean:clean {execution: default-clean}]
  [INFO] Deleting file set: /home/cerdlin1/SEEP-master/target (included: [**], excluded: [])
  [INFO] No goals needed for project - skipping
  [INFO] [assembly:single {execution: default-cli}]
  [WARNING] Cannot include project artifact: uk.ac.imperial.lsds.seep:seep:pom:0.0.1-SNAPSHOT; it doesn't have an associated file or directory.
  [INFO] Building jar: /home/cerdlin1/SEEP-master/target/seep-0.0.1-SNAPSHOT.jar
  [INFO] ------------------------------------------------------------------------
  [INFO] Building seep-system
  [INFO]    task-segment: [clean, compile, assembly:single]
  [INFO] ------------------------------------------------------------------------
  [INFO] [clean:clean {execution: default-clean}]
  [INFO] Deleting file set: /home/cerdlin1/SEEP-master/seep-system/target (included: [**], excluded: [])
  [INFO] [resources:resources {execution: default-resources}]
  [INFO] Using 'UTF-8' encoding to copy filtered resources.
  [INFO] Copying 3 resources
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error building POM (may not be this project's POM).

Project ID: null:jetty-project:pom:9.0.0.v20130308

Reason: Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.eclipse.jetty:jetty-server:jar': Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308
  org.eclipse.jetty:jetty-server:jar:9.0.0.v20130308

from the specified remote repositories:
  uk.ac.imperial.lsds.seep-system (file:///home/cerdlin1/SEEP-master/seep-system/libs),
  central (http://repo1.maven.org/maven2)

Path to dependency: 
    1) uk.ac.imperial.lsds.seep:seep-system:jar:0.0.1-SNAPSHOT

```
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:711)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.eclipse.jetty:jetty-server:jar': Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308
  org.eclipse.jetty:jetty-server:jar:9.0.0.v20130308

from the specified remote repositories:
  uk.ac.imperial.lsds.seep-system (file:///home/cerdlin1/SEEP-master/seep-system/libs),
  central (http://repo1.maven.org/maven2)

Path to dependency: 
    1) uk.ac.imperial.lsds.seep:seep-system:jar:0.0.1-SNAPSHOT

```
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:430)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:74)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:316)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:304)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1499)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:442)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
```

Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'org.eclipse.jetty:jetty-server:jar': Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:200)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedArtifact(MavenMetadataSource.java:94)
    at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:387)
    ... 23 more
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.eclipse.jetty:jetty-parent for project: null:jetty-project:pom:9.0.0.v20130308 for project null:jetty-project:pom:9.0.0.v20130308
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1407)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:255)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:163)
    ... 25 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Not a v4.0.0 POM. for project org.eclipse.jetty:jetty-parent at /home/cerdlin1/.m2/repository/org/eclipse/jetty/jetty-parent/20/jetty-parent-20.pom
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1599)
    at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1571)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:562)
    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
    ... 29 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Thu Feb 18 13:41:13 IST 2016
[INFO] Final Memory: 27M/311M
[INFO] --------------------------

**Comment by pgaref** [comment]
Can you post here the output of: mvn -version?

Thanks

**Comment by raulcf** [comment]
Hi @shibilyj 

could you provide details on what is the use case you want to solve with SEEP? We have a more updated codebase SEEPng that you may want to use instead, as it is actively maintained, unlike this one.

thanks!

**Comment by shibilyj** [comment]
My mvn version is
Apache Maven 2.2.1 (rdebian-1)
Java version: 1.6.0_24
Java home: /usr/lib/jvm/java-6-sun-1.6.0.24/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux" version: "2.6.32-30-generic" arch: "i386" Family: "unix"
cerdlin1@cerdlin1-desktop:~/SEEP-master$ ^C

**Comment by shibilyj** [comment]
My aim is to run the GC14 solution to study the framework.
Then my aim to utilize this software to detect real time events received form smart energy meters for smart grid.
